version: '3.5'
services:
  web:
    build:
      context: .
      dockerfile: ./ci/local/golang/Dockerfile
      args:
        UID: "${uid}"
        GID: "${gid}"
    ports:
      - "8080:8080"
    volumes:
    - .:/go/src/app